<?php
//check for any post variables. if there are any then check for csv file. explode the data by newline and then further by commas.
?>
<!doctype html>
<html lang="en">
<head>
    <title>VisualCSV</title>
    <style type="text/css">
        table, th, td{
            border-collapse:collapse;
            border:1px solid black;
        }
        th, td{
            padding:5px;
        }
    </style>
</head>
<body>
    <h1>VisualCSV</h1>
    <div id="results"></div>
    <form action="./" method="post" enctype="multipart/form-data">
        <label for="file">Choose a csv file to upload:</label>
        <input type="file" name="file" id="file"><br>
        <input type="submit" name="submit" value="Submit">
    </form>
</body>
<script type="text/javascript">
    //standard functions
    function drawtable(){
        cols=axis.length;
        rows=values.length;
        var row = document.createElement("tr");
        for (var i=0;i<cols;i++) {
            row.innerHTML+="<th>"+axis[i]+"</th>"
        }
        var table=document.createElement("table");
        table.appendChild(row);
        for(var i=0;i<rows;i++){
            row = document.createElement("tr");
            for (var j=0;j<cols;j++) {
                row.innerHTML+="<td>"+diction[j][values[i][j]]+"</td>";
            }
            table.appendChild(row);
        }
        document.getElementById("results").appendChild(table);
    }
    function drawchart(){
        //everything to draw the chart
    }
    //the below lines should be generated by php script later on
    axis=["Name","Age","Gender","City","Mobile Operator"];
    diction=[
             ["Sara","Floriana","Raghav","Meghna","Sumit"],
             ["32","36","24","21","27"],
             ["Female","Male"],
             ["Delhi","Mumbai"],
             ["Airtel","Vodafone"]
            ];
    values = [[0,0,0,0,0],[1,1,0,0,1],[2,2,1,1,1],[3,3,0,1,1],[4,4,1,0,0]];
    drawtable();
    drawchart();
</script>
</html>
